# Generated by Django 3.1.2 on 2021-02-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('task_id', models.CharField(max_length=128, unique=True, verbose_name='任务ID')),
                ('task_name', models.CharField(max_length=32, verbose_name='任务名称')),
                ('task_hosts', models.JSONField(blank=True, default=[], null=True, verbose_name='目标主机')),
                ('script_file', models.CharField(blank=True, max_length=128, null=True, verbose_name='执行脚本')),
                ('script_cmd', models.CharField(blank=True, max_length=1024, null=True, verbose_name='执行命令')),
                ('task_state', models.BooleanField(default=True, verbose_name='任务执行结果')),
                ('task_result', models.JSONField(blank=True, default={}, null=True, verbose_name='返回结果')),
                ('exec_interval', models.IntegerField(default=0, verbose_name='运行时长(s)')),
                ('src_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='来源IP')),
                ('create_user', models.CharField(blank=True, max_length=50, null=True, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '任务历史',
                'verbose_name_plural': '任务历史',
            },
        ),
    ]
