# Generated by Django 3.1.2 on 2021-02-21 13:01

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskhistory',
            name='script_cmd',
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='task_hosts',
            field=models.JSONField(default=base.models.JSONFieldDefault, verbose_name='目标主机'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='task_result',
            field=models.JSONField(blank=True, default=base.models.JSONFieldDefault, null=True, verbose_name='返回结果'),
        ),
    ]
