# Generated by Django 3.1.2 on 2021-03-17 00:00

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('title', models.CharField(max_length=32, verbose_name='IDC名称')),
                ('position', models.CharField(max_length=32, verbose_name='设备位置')),
            ],
            options={
                'verbose_name': '机房表',
                'verbose_name_plural': '机房表',
            },
        ),
        migrations.AlterModelOptions(
            name='cmdbbase',
            options={'verbose_name': 'CMDB基表', 'verbose_name_plural': 'CMDB基表'},
        ),
        migrations.RemoveField(
            model_name='cmdbbase',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cmdbbase',
            name='ssh',
        ),
        migrations.AddField(
            model_name='cmdbbase',
            name='account',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='云账号'),
        ),
        migrations.AddField(
            model_name='cmdbbase',
            name='create_user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='cmdbbase',
            name='disks',
            field=models.JSONField(default=base.models.JSONMulFieldDefault, verbose_name='磁盘'),
        ),
        migrations.AddField(
            model_name='cmdbbase',
            name='expired_time',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='过期时间'),
        ),
        migrations.AddField(
            model_name='cmdbbase',
            name='instance_charge_type',
            field=models.CharField(blank=True, choices=[('PrePaid', '包年包月'), ('PostPaid', '按量')], max_length=32, null=True, verbose_name='主机付费类型'),
        ),
        migrations.AddField(
            model_name='cmdbbase',
            name='instance_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='实例ID'),
        ),
        migrations.AddField(
            model_name='cmdbbase',
            name='instance_type',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='实例类型'),
        ),
        migrations.AddField(
            model_name='cmdbbase',
            name='os_platform',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='操作系统'),
        ),
        migrations.AddField(
            model_name='cmdbbase',
            name='os_version',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='系统版本'),
        ),
        migrations.AddField(
            model_name='cmdbbase',
            name='root_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='主账号ID'),
        ),
        migrations.AddField(
            model_name='cmdbbase',
            name='security_group_ids',
            field=models.JSONField(default=base.models.JSONMulFieldDefault, verbose_name='安全组'),
        ),
        migrations.AddField(
            model_name='cmdbbase',
            name='subnet_id',
            field=models.CharField(default='', max_length=100, verbose_name='交换机ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cmdbbase',
            name='vpc_id',
            field=models.CharField(default='', max_length=100, verbose_name='VPC ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cmdbbase',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cmdbbase',
            name='public_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='公网IP地址'),
        ),
        migrations.DeleteModel(
            name='SSH',
        ),
    ]
