# Generated by Django 3.1.2 on 2021-03-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20210317_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmdbbase',
            name='create_server_time',
            field=models.CharField(default='0000-00-00 00:00:00', max_length=100, verbose_name='实例创建时间'),
        ),
        migrations.AddField(
            model_name='cmdbbase',
            name='image_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='镜像ID'),
        ),
        migrations.AlterField(
            model_name='cmdbbase',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
