# Generated by Django 3.1.2 on 2021-03-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20210317_0014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmdbbase',
            old_name='region',
            new_name='region_name',
        ),
        migrations.RenameField(
            model_name='cmdbbase',
            old_name='zone',
            new_name='zone_name',
        ),
        migrations.AddField(
            model_name='cmdbbase',
            name='region_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='地域ID'),
        ),
        migrations.AddField(
            model_name='cmdbbase',
            name='zone_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='可用区ID'),
        ),
    ]
