# Generated by Django 3.1.2 on 2021-03-17 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20210317_0016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IDC',
        ),
    ]
