# Generated by Django 3.1.2 on 2021-03-17 00:23

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_delete_idc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdbbase',
            name='security_group_ids',
            field=models.JSONField(blank=True, default=base.models.JSONMulFieldDefault, null=True, verbose_name='安全组'),
        ),
        migrations.AlterField(
            model_name='cmdbbase',
            name='vpc_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='VPC ID'),
        ),
    ]
