# Generated by Django 3.1.2 on 2021-03-17 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_auto_20210317_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdbbase',
            name='subnet_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='交换机ID'),
        ),
    ]
