# Generated by Django 3.1.2 on 2021-03-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_auto_20210317_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdbbase',
            name='region_name',
            field=models.CharField(default='', max_length=100, verbose_name='机房/地域'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cmdbbase',
            name='zone_name',
            field=models.CharField(default='', max_length=100, verbose_name='位置/可用区'),
            preserve_default=False,
        ),
    ]
