# Generated by Django 3.1.2 on 2021-04-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0011_auto_20210331_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmdbbase',
            name='eip_ip',
            field=models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='弹性IP地址'),
        ),
    ]
