# Generated by Django 3.1.2 on 2021-04-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0013_cmdbbase_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdbbase',
            name='eip_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='弹性IP地址'),
        ),
        migrations.AlterField(
            model_name='cmdbbase',
            name='public_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='公网IP地址'),
        ),
    ]
