# Generated by Django 3.1.2 on 2021-04-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0015_auto_20210401_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmdbbase',
            name='platform',
            field=models.CharField(choices=[('aws', '亚马逊'), ('ali', '阿里云'), ('ten', '腾讯云'), ('hw', '华为云'), ('azure', '微软云'), ('other', '其它')], default=0, max_length=50, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='cmdbbase',
            name='state',
            field=models.CharField(choices=[('running', '运行'), ('stopped', '停止')], max_length=50, verbose_name='运行状态'),
        ),
        migrations.AlterField(
            model_name='cmdbbase',
            name='type',
            field=models.CharField(choices=[('idc', 'IDC机房'), ('cloud', '云主机'), ('container', '容器')], max_length=50, verbose_name='机器类型'),
        ),
    ]
