# Generated by Django 3.1.2 on 2021-06-07 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmdb', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='节点名称-英文')),
                ('name_cn', models.CharField(blank=True, max_length=100, null=True, verbose_name='节点名称-中文')),
                ('abspath', models.CharField(db_index=True, max_length=200, verbose_name='abspath')),
                ('appkey', models.CharField(db_index=True, max_length=200, verbose_name='appkey')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='service_tree.servicetree', verbose_name='父级')),
            ],
            options={
                'verbose_name': '服务树基础表',
                'verbose_name_plural': '服务树基础表',
            },
        ),
        migrations.CreateModel(
            name='NodeLinkServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('cmdbs', models.ManyToManyField(blank=True, null=True, related_name='link_server', to='cmdb.TableData')),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service_tree.servicetree', verbose_name='节点')),
            ],
            options={
                'verbose_name': '节点关联主机',
                'verbose_name_plural': '节点关联主机',
            },
        ),
        migrations.CreateModel(
            name='NodeLinkOperaPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service_tree.servicetree', verbose_name='节点')),
                ('read_member', models.ManyToManyField(blank=True, null=True, related_name='read_member', to=settings.AUTH_USER_MODEL, verbose_name='read 成员')),
                ('write_member', models.ManyToManyField(blank=True, null=True, related_name='write_member', to=settings.AUTH_USER_MODEL, verbose_name='write 成员')),
            ],
            options={
                'verbose_name': '节点操作权限',
                'verbose_name_plural': '节点操作权限',
            },
        ),
        migrations.CreateModel(
            name='NodeJoinTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('key', models.CharField(db_index=True, max_length=32, verbose_name='Key')),
                ('value', jsonfield.fields.JSONField(default={}, verbose_name='Value')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_tree.servicetree', verbose_name='节点')),
            ],
            options={
                'verbose_name': '节点关联Tag',
                'verbose_name_plural': '节点关联Tag',
            },
        ),
    ]
