# Generated by Django 3.1.2 on 2021-02-27 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodelinkoperapermission',
            name='node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service_tree.servicetree', verbose_name='节点'),
        ),
    ]
