# Generated by Django 3.1.2 on 2021-02-20 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('name', models.CharField(help_text='名称', max_length=128, verbose_name='名称')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'role',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Router',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('title', models.CharField(help_text='标题', max_length=128, verbose_name='标题')),
                ('index', models.CharField(help_text='索引', max_length=64, verbose_name='索引')),
                ('desc', models.CharField(blank=True, help_text='描述', max_length=256, null=True, verbose_name='描述')),
                ('icon', models.CharField(blank=True, help_text='图表', max_length=256, null=True, verbose_name='图表')),
                ('routeName', models.CharField(blank=True, help_text='路有名', max_length=128, null=True, verbose_name='路由名')),
                ('go', models.CharField(blank=True, help_text='URL', max_length=128, null=True, verbose_name='URL')),
                ('isParent', models.BooleanField(default=True, verbose_name='是否顶级路由')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='permission.router', verbose_name='父路由')),
                ('role', models.ManyToManyField(blank=True, related_name='router', to='permission.Role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '前端路由',
                'verbose_name_plural': '前端路由',
                'db_table': 'route',
            },
        ),
        migrations.CreateModel(
            name='RoleBind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('ptype', models.CharField(default='g', max_length=1, verbose_name='权限类型')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_bind', to='permission.role', verbose_name='角色')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_bind', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '角色绑定',
                'verbose_name_plural': '角色绑定',
                'db_table': 'role_bind',
                'unique_together': {('user', 'role')},
            },
        ),
        migrations.CreateModel(
            name='PermRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='变更时间')),
                ('remark', models.CharField(blank=True, max_length=1024, null=True, verbose_name='备注')),
                ('name', models.CharField(help_text='名称', max_length=256, verbose_name='名称')),
                ('ptype', models.CharField(default='p', max_length=1, verbose_name='权限类型')),
                ('path', models.CharField(max_length=128, verbose_name='api路径')),
                ('method', models.CharField(max_length=128, verbose_name='请求方法')),
                ('role', models.ManyToManyField(blank=True, related_name='perm_rule', to='permission.Role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '权限规则',
                'verbose_name_plural': '权限规则',
                'db_table': 'perm_rule',
                'unique_together': {('name', 'path', 'method')},
            },
        ),
    ]
